name: Create zip file of production code upon release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
      - run: npm run build
      # create a zip file containing the 'dist' folder
      - name: Create release zip
        run: cd dist && zip -r ../lightswitch-dist.zip . && cd ..
      # upload the created zip as an asset to the published release
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lightswitch-dist.zip
